eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085
spring:
  application:
    name: client-app
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
